### ISSUE TITLE
StiDataAdapter preg_match error

### ISSUE THREAD

**Issue by qwasyx0** [stimulsoft/Samples-Reports.PHP-for-Laravel#1]
First of all thank you so much for a laravel example, I have made custom implementation but still had to put main login in javascript functions in blade instead of HandlerController.

I have some issues:

<img width="1507" alt="Snímek obrazovky 2023-06-08 v 18 21 55" src="https://github.com/stimulsoft/Samples-Reports.PHP-for-Laravel/assets/43924784/96bb9fa1-1fc9-4cb4-ba7d-071bfa690bbf">

According to my log some values coming to StiDataAdapter function deletecType($value) can be null (in devtools handler.php request it's rows[0], quick fix is to return string:

```php
protected function detectType($value)
    {
      // check for empty string
        if (empty($value)) {
            return 'string';
        }

        if (preg_match('~[^\x20-\x7E\t\r\n]~', $value) > 0)
            return 'array';

        if (is_numeric($value)) {
            if (strpos($value, '.') !== false)
                return 'number';
            return 'int';
        }

        if (\DateTime::createFromFormat('Y-m-d H:i:s', $value) !== false ||
            \DateTime::createFromFormat('Y-m-d', $value) !== false ||
            \DateTime::createFromFormat('Y-M-d', $value) !== false ||
            \DateTime::createFromFormat('H:i:s', $value) !== false)
            return 'datetime';

        if (is_string($value))
            return 'string';

        return 'array';
    }
```

When printing/downloading as pdf the report changes:

Preview in designer:
<img width="802" alt="Snímek obrazovky 2023-06-08 v 18 40 07" src="https://github.com/stimulsoft/Samples-Reports.PHP-for-Laravel/assets/43924784/eb25573b-ab7a-4d0b-b09f-d3a647757d88">

Save -> Adobe PDF (font is not the same as set in Text field, should be calibri, also bold is not working):
<img width="802" alt="Snímek obrazovky 2023-06-08 v 18 40 21" src="https://github.com/stimulsoft/Samples-Reports.PHP-for-Laravel/assets/43924784/bdcb7dc5-b1da-4ba6-a72c-91f303928ce4">

Print -> Print (same issues but also missing some conditional Text fields):
<img width="1023" alt="Snímek obrazovky 2023-06-08 v 18 42 39" src="https://github.com/stimulsoft/Samples-Reports.PHP-for-Laravel/assets/43924784/ebc8a3af-3f95-4419-8838-4f10dc65056f">

This is how my condition is set:
<img width="1023" alt="Snímek obrazovky 2023-06-08 v 18 49 00" src="https://github.com/stimulsoft/Samples-Reports.PHP-for-Laravel/assets/43924784/d20049e5-a3e5-4102-a9ee-58868ef88f09">

**Comment by VladimirHot** [comment]
Hello, 

The issue with StiDataAdapter has been fixed.

Other problems are transferred to the internal tickets. To clarify the status of the solution, please write to support@stimulsoft.com

Thank you.
